### ISSUE TITLE
Re-implementing embind_register_function in Go

### ISSUE THREAD

**Issue by agnivade** [jerbob92/wazero-emscripten-embind#24]
Apologies for a slightly off-topic issue, but I think this repo might be the closest related.

I am trying to compile https://github.com/ggerganov/whisper.cpp to wasi and run it via wazero. I have successfully compiled, and used this repo to stub out the imports.

But the repo uses `EMSCRIPTEN_BINDINGS` to expose the relevant functions https://github.com/ggerganov/whisper.cpp/blob/6559b538e5e05cfa199c15d46ca5bd0edd353974/examples/whisper.wasm/emscripten.cpp#L19 which are actually registered post instantiation via the `__embind_register_function`. 

Now all of this is implemented in the js that emscripten generates via some heavy reflection. So I am actually unable to use the module until I implement the function registration logic to expose the functions in the module and then use them. I am not sure if I have to re-implement this function registering logic all over in Go, or is there a way to bind and expose these functions during compile time itself.

These are my linker flags: 
```
/usr/bin/em++    -Wall        -Wextra    -Wpedantic    -Wcast-qual  --no-entry  -lembind -g -O1 -DNDEBUG  --bind
  -s STANDALONE_WASM    
 -s INITIAL_MEMORY=2000MB    
 -s TOTAL_MEMORY=2000MB     
-s FORCE_FILESYSTEM=1    
 -s EXPORTED_RUNTIME_METHODS="['print', 'printErr', 'ccall', 'cwrap']"        
   @CMakeFiles/libmain.dir/objects1.rsp -o ../../bin/libmain.js @CMakeFiles/libmain.dir/linklibs.rsp
```

Any help would be much appreciated!

**Comment by agnivade** [comment]
I have changed the code to compile without threads. That's not an issue.

But I figured out the problem! It seems like the code I am compiling is generating a signature mismatch.

```
import func[env._embind_register_function]: signature mismatch: i32i32i32i32i32i32_v != i32i32i32i32i32i32i32_v
```
It seems like your code has 7 params, but my generated wasm file has 6 params. 

This is yours:
```
b.NewFunctionBuilder().
		WithName("_embind_register_function").
		WithParameterNames("name", "argCount", "rawArgTypesAddr", "signature", "rawInvoker", "fn", "isAsync").
		WithGoModuleFunction(internal.RegisterFunction, []api.ValueType{api.ValueTypeI32, api.ValueTypeI32, api.ValueTypeI32, api.ValueTypeI32, api.ValueTypeI32, api.ValueTypeI32, api.ValueTypeI32}, []api.ValueType{}).
		Export("_embind_register_function")
```

This is the emscripten JS glue:
```
function __embind_register_function(name, argCount, rawArgTypesAddr, signature, rawInvoker, fn) {
```

The difference being the `isAsync` parameter. Is there any way I can create a stub, but still call the `internal.RegisterFunction` by ignoring `isAsync` ?

I can clearly do:
```go
builder.NewFunctionBuilder().WithFunc(func(ctx context.Context, p1, p2, p3, p4, p5, p6 int32) {
	 	log.Printf("_embind_register_function called-: %d %d %d %d %d %d", p1, p2, p3, p4, p5, p6)
 }).Export("_embind_register_function")
```

But I need to have access to your `internal.RegisterFunction`. 

Any help would be much appreciated. The cpp codebase is not written by me, so I am a bit helpless to change the generated wasm code.

**Comment by jerbob92** [comment]
That's because Emscripten changed the signature of the function in the most recent version, I have already started working on implementing that correctly: https://github.com/jerbob92/wazero-emscripten-embind/pull/22
However, it's not functional yet.

You can fix this by compiling using Emscripten 3.1.47

**Comment by agnivade** [comment]
Thanks that was it! I actually accidentally used the latest and then ran into #22. Then I set to 3.1.47 and everything is working correctly now. :tada: 

Looks like maintaining emscripten compatiblity is going to be an headache as they seem to be changing function signatures very frequently. :thinking:

**Comment by jerbob92** [comment]
Ah, nice! 

Yeah you're absolutely right, but it is what it is, Emscripten can change the functions signatures and implementation logic any time since they generate the wasm and JS glue at the same time, that is problematic for this project but I think it's doable when the changes aren't too big. At some point I might have to link versions of this project to a specific Emscripten version to make my life easier.

**Comment by jerbob92** [comment]
@agnivade the changes in #22 now successfully pas all tests on all versions 3.1.44 - 3.1.50, do you mind testing that out?

**Comment by agnivade** [comment]
Thanks, I am stuck in some other problem at the moment :P But I will when I get a chance.
